function [state, transition] = updateState(state, planner, world, scenario, collision, cfg)
%UPDATESTATE Adapt world/planner contracts to the shared numeric behaviour step.
oldName=state.name;
goal=norm(world.ego.positionWorldM-scenario.goalPositionWorldM)<=cfg.goalToleranceM;
nearest=Inf;
for k=1:numel(world.agents)
    nearest=min(nearest,norm(world.agents(k).positionWorldM-world.ego.positionWorldM));
end
lateral=abs(planner.selectedTrajectory.positionsWorldM(end,2)-world.ego.positionWorldM(2))>.6;
[code,state.clearSinceS,reasonCode]=pathweaver.behavior.stepDecision( ...
    pathweaver.behavior.stateCode(oldName),state.clearSinceS,world.timestampS, ...
    planner.riskScore,planner.minimumTtcS,planner.emergencyFlag,planner.selectedTrajectory.isFeasible, ...
    goal,collision,lateral,nearest,pathweaver.behavior.decisionLimits(cfg));
names=["CRUISE","FOLLOW","YIELD","AVOID","EMERGENCY_BRAKE","GOAL_REACHED","COLLISION"];
reasons=["conditions nominal","terminal state retained","footprint collision detected", ...
    "ego entered goal region","no feasible candidate; braking, safety not guaranteed", ...
    "bounded braking selected by planner","TTC unavailable; fail-closed braking", ...
    "predicted footprint contact below emergency threshold","crossing risk or TTC threshold", ...
    "selected lateral avoidance trajectory","nearby road user limits progress", ...
    "emergency-clearance dwell","emergency hysteresis"];
state.name=names(code+1); state.reason=reasons(reasonCode);
transition=struct('occurred',state.name~=oldName,'timestampS',world.timestampS, ...
    'from',oldName,'to',state.name,'reason',state.reason);
if transition.occurred, state.lastTransitionTimeS=world.timestampS; end
end
