function validateEgoState(ego)
%VALIDATEEGOSTATE Validate units, shape, and numerical invariants.
required = {'positionWorldM','headingRad','speedMps','accelerationMps2', ...
    'steeringRad','timestampS'};
assert(all(isfield(ego, required)), 'PathWeaver:InvalidEgoState', ...
    'EgoState is missing required fields.');
values = [ego.positionWorldM ego.headingRad ego.speedMps ...
    ego.accelerationMps2 ego.steeringRad ego.timestampS];
assert(numel(ego.positionWorldM) == 2 && all(isfinite(values)), ...
    'PathWeaver:InvalidEgoState', 'EgoState values must be finite.');
assert(ego.speedMps >= 0 && ego.timestampS >= 0, ...
    'PathWeaver:InvalidEgoState', 'Speed and timestamp must be nonnegative.');
end
