function summary=aggregateResults(results)
%AGGREGATERESULTS Counts include invalid/timeout outcomes, never only successes.
rows={};
for preset=unique(results.preset,'stable')'
    for mode=["baseline","risk-aware"]
        r=results(results.preset==preset & results.mode==mode,:);
        row=struct('preset',preset,'mode',mode,'runs',height(r), ...
            'collisions',sum(r.status=="collision"),'completions',sum(r.status=="goal_reached"), ...
            'timeouts',sum(r.status=="timeout"),'invalid',sum(r.status=="invalid"), ...
            'minimumClearanceM',min(r.minimumClearanceM,[],'omitnan'), ...
            'finiteTtcRuns',sum(isfinite(r.minimumTtcS)), ...
            'unavailableTtcSamples',sum(r.ttcUnavailableSamples,'omitnan'), ...
            'meanCompletionTimeS',mean(r.timeToGoalS,'omitnan'), ...
            'meanIntegratedJerkMps2',mean(r.integratedAbsoluteJerkMps2,'omitnan'), ...
            'meanOfRunMeanLatencyMs',1000*mean(r.averagePlannerLatencyS,'omitnan'), ...
            'meanOfRunP95LatencyMs',1000*mean(r.p95PlannerLatencyS,'omitnan'));
        rows{end+1}=struct2table(row); %#ok<AGROW>
    end
end
summary=vertcat(rows{:});
end
