function scenario = createVillageCrossing(cfg)
%CREATEVILLAGECROSSING Create deterministic lane-agnostic scenario state.
stream=RandStream('mt19937ar','Seed',cfg.seed);
sc = cfg.scenario;
x = (0:sc.boundarySampleM:sc.roadLengthM)';
[leftY, rightY] = pathweaver.core.roadBounds(x, sc);
pedestrian = sc.pedestrian;
twoWheeler = sc.twoWheeler;
pedestrian.positionWorldM(1) = pedestrian.positionWorldM(1) + ...
    sc.longitudinalJitterStdM*randn(stream);
twoWheeler.positionWorldM(1) = twoWheeler.positionWorldM(1) + ...
    sc.longitudinalJitterStdM*randn(stream);
scenario = struct('name', sc.name, 'timeS', 0, 'roadXWorldM', x, ...
    'leftBoundaryWorldM', [x leftY], 'rightBoundaryWorldM', [x rightY], ...
    'agents', [rmfield(pedestrian, {'crossingStartS','crossingSpeedMps'}) ...
        twoWheeler], 'staticObstacles', sc.pothole, ...
    'goalPositionWorldM', sc.goalPositionWorldM, ...
    'pedestrianTriggered', false, 'seed', cfg.seed,'preset',sc.preset);
scenario.parameters=struct('pedestrianXWorldM',pedestrian.positionWorldM(1), ...
    'pedestrianYWorldM',pedestrian.positionWorldM(2),'crossingStartS',pedestrian.crossingStartS, ...
    'crossingSpeedMps',pedestrian.crossingSpeedMps,'twoWheelerXWorldM',twoWheeler.positionWorldM(1), ...
    'twoWheelerSpeedMps',norm(twoWheeler.velocityWorldMps),'egoInitialSpeedMps',sc.egoInitial.speedMps, ...
    'longitudinalJitterStdM',sc.longitudinalJitterStdM);
end
