function world = worldState(scenario, ego)
%WORLDSTATE Explicit simulated-ground-truth adapter boundary.
world = struct('timestampS', scenario.timeS, 'ego', ego, ...
    'agents', scenario.agents, 'staticObstacles', scenario.staticObstacles, ...
    'leftBoundaryWorldM', scenario.leftBoundaryWorldM, ...
    'rightBoundaryWorldM', scenario.rightBoundaryWorldM, ...
    'source', "SIMULATED WORLD STATE");
end
